=== huolibo/test/System/Schemas/element_template.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tdasset.tdengine.com/schemas/element_template.json",
  "title": "element-template",
  "description": "schema of a element template",
  "type": "object",
  "required": [
    "id",
    "name"
  ],
  "properties": {
    "id": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "dirName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "baseTemplateIds": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "namingPattern": {
      "type": "string"
    },
    "generalInfo": {
      "$ref": "./general_info.json"
    },
    "attributeTemplates": {
      "type": "array",
      "items": {
        "$ref": "./element_attribute.json"
      }
    },
    "notifyRuleTemplate": {
      "$ref": "./notify_rule_template.json"
    },
    "allowExtensions": {
      "type": "boolean"
    },
    "baseTemplateOnly": {
      "type": "boolean"
    },
    "keywordsDesc": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "icon": {
      "type": "string"
    }
  }
}

=== huolibo/test/Libraries/ElementTemplates/能源计量表/meta.json
{
  "id" : 2055156146022528,
  "name" : "能源计量表",
  "description" : "能源计量表",
  "namingPattern" : "${KEYWORD1}",
  "dirName" : "能源计量表",
  "generalInfo" : {
    "location" : {
      "altitude" : 4866.066268246121,
      "latitude" : 66.78154173940581,
      "longitude" : 117.51451782891564
    },
    "virtualStableName" : "vst_能源计量表_i7i6zt"
  },
  "attributeTemplates" : [ {
    "id" : 2055156146231424,
    "name" : "瞬时消耗值",
    "description" : "瞬时消耗值",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "displayDigits" : 2,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "瞬时消耗值",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "meter_value",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156146526336,
    "name" : "所属厂区",
    "description" : "厂区名称",
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 50,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "所属厂区",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "plant",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156146833536,
    "name" : "命名模式",
    "description" : "设备命名模式的占位符",
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 50,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "命名模式",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "namingPattern",
      "autoCreated" : false
    }
  } ],
  "allowExtensions" : true,
  "baseTemplateOnly" : false,
  "keywordsDesc" : {
    "KEYWORD1" : "表具名称"
  }
}

=== huolibo/test/Libraries/ElementTemplates/连续动力设备/meta.json
{
  "id" : 2055156142794880,
  "name" : "连续动力设备",
  "description" : "连续动力设备",
  "namingPattern" : "${KEYWORD1}",
  "dirName" : "连续动力设备",
  "generalInfo" : {
    "location" : {
      "altitude" : 308.1036630235405,
      "latitude" : -44.46118949602416,
      "longitude" : 114.67028126524986
    },
    "virtualStableName" : "vst_连续动力设备_gl6ss4"
  },
  "attributeTemplates" : [ {
    "id" : 2055156142995584,
    "name" : "振动幅度",
    "description" : "振动幅度",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "defaultUom" : 2055156138289280,
    "displayUom" : 2055156138289280,
    "displayDigits" : 2,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "振动幅度",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "vibration",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156143265920,
    "name" : "运行电流",
    "description" : "运行电流",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "defaultUom" : 2144441927,
    "displayUom" : 2144441927,
    "displayDigits" : 2,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "运行电流",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "pump_current",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156143560832,
    "name" : "轴承温度",
    "description" : "轴承温度",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "defaultUom" : 1153421915,
    "displayUom" : 1153421915,
    "displayDigits" : 1,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "轴承温度",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "bearing_temp",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156143814784,
    "name" : "所属厂区",
    "description" : "厂区名称",
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 50,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "所属厂区",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "plant",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156144339072,
    "name" : "命名模式",
    "description" : "设备命名模式的占位符",
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 50,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "命名模式",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "namingPattern",
      "autoCreated" : false
    }
  } ],
  "allowExtensions" : true,
  "baseTemplateOnly" : false,
  "keywordsDesc" : {
    "KEYWORD1" : "设备名称"
  }
}

=== huolibo/test/Libraries/ElementTemplates/mysql模板/meta.json
{
  "id" : 2055478444214400,
  "name" : "mysql模板",
  "description" : "",
  "baseTemplateIds" : [ ],
  "namingPattern" : "${Template#name}",
  "dirName" : "mysql模板",
  "generalInfo" : {
    "categories" : [ ],
    "location" : { },
    "additionalAttributes" : [ ],
    "virtualStableName" : "vst_mysql模板_mo90en"
  },
  "attributeTemplates" : [ {
    "id" : 2055478628563072,
    "name" : "metric",
    "description" : "",
    "constantItem" : false,
    "hidden" : false,
    "excluded" : false,
    "categories" : [ 22 ],
    "valueType" : "Int",
    "defaultValue" : "3",
    "displayDigits" : -5,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055478375004288,
      "dbName" : "idmp",
      "childTable" : "",
      "columnName" : "metric",
      "sourceDBName" : "idmp",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "id",
      "errMsg" : "",
      "verified" : false,
      "autoCreated" : false
    },
    "additionalProperties" : [ ],
    "traits" : [ ],
    "childAttributes" : [ ]
  }, {
    "id" : 2055478767712384,
    "name" : "tag",
    "description" : "",
    "constantItem" : false,
    "hidden" : false,
    "excluded" : false,
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 64,
    "defaultValue" : "",
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055478375004288,
      "dbName" : "idmp",
      "childTable" : "",
      "columnName" : "tag",
      "sourceDBName" : "idmp",
      "sourceTimestampColumnName" : "ts",
      "tagQueryMode" : "SIMPLE",
      "tagReadMode" : "LATEST_ROW",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "name",
      "errMsg" : "",
      "verified" : false,
      "autoCreated" : false
    },
    "additionalProperties" : [ ],
    "traits" : [ ],
    "childAttributes" : [ ]
  } ],
  "allowExtensions" : true,
  "baseTemplateOnly" : false,
  "keywordsDesc" : {
    "KEYWORD1" : "表名称"
  }
}

=== huolibo/test/Libraries/ElementTemplates/间歇反应设备/meta.json
{
  "id" : 2055156139915392,
  "name" : "间歇反应设备",
  "description" : "间歇反应釜",
  "namingPattern" : "${KEYWORD1}",
  "dirName" : "间歇反应设备",
  "generalInfo" : {
    "location" : {
      "altitude" : 3760.286259458085,
      "latitude" : -38.24793798295281,
      "longitude" : -150.40136835424255
    },
    "virtualStableName" : "vst_间歇反应设备_nq0wah"
  },
  "attributeTemplates" : [ {
    "id" : 2055156140673152,
    "name" : "工艺温度",
    "description" : "工艺温度",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "defaultUom" : 1153421915,
    "displayUom" : 1153421915,
    "displayDigits" : 2,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "工艺温度",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "temperature",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156141037696,
    "name" : "工艺压力",
    "description" : "工艺压力",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "defaultValue" : "0",
    "defaultUom" : 4899462,
    "displayUom" : 4899462,
    "displayDigits" : 2,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "工艺压力",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "pressure",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156141353088,
    "name" : "设备液位",
    "description" : "设备液位",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "defaultUom" : 1204723484,
    "displayUom" : 1204723484,
    "displayDigits" : 2,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "设备液位",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "level",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156141664384,
    "name" : "运行状态",
    "description" : "运行状态",
    "categories" : [ 22 ],
    "valueType" : "Int",
    "displayDigits" : 0,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "运行状态",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "reactor_state",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156141926528,
    "name" : "生产批次号",
    "description" : "生产批次号",
    "categories" : [ 22 ],
    "valueType" : "Varchar",
    "valueLength" : 32,
    "displayDigits" : 0,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "生产批次号",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "batch_tag",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156142205056,
    "name" : "所属厂区",
    "description" : "厂区名称",
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 50,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "所属厂区",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "plant",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156142504064,
    "name" : "命名模式",
    "description" : "设备命名模式的占位符",
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 50,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "命名模式",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "namingPattern",
      "autoCreated" : false
    }
  } ],
  "allowExtensions" : true,
  "baseTemplateOnly" : false,
  "keywordsDesc" : {
    "KEYWORD1" : "反应釜名称"
  }
}

=== huolibo/test/Libraries/ElementTemplates/质检中心设备/meta.json
{
  "id" : 2055156144650368,
  "name" : "质检中心设备",
  "description" : "质检中心设备",
  "namingPattern" : "${KEYWORD1}",
  "dirName" : "质检中心设备",
  "generalInfo" : {
    "location" : {
      "altitude" : 5273.069340374878,
      "latitude" : 41.968726580446486,
      "longitude" : 157.63710922214352
    },
    "virtualStableName" : "vst_质检中心设备_qnidoz"
  },
  "attributeTemplates" : [ {
    "id" : 2055156144928896,
    "name" : "产品纯度",
    "description" : "产品纯度",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "displayDigits" : 2,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "产品纯度",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "gc_purity",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156145195136,
    "name" : "水分含量",
    "description" : "水分含量",
    "categories" : [ 22 ],
    "valueType" : "Double",
    "displayDigits" : 2,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineMetric",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "水分含量",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "gc_moisture",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156145457280,
    "name" : "所属厂区",
    "description" : "厂区名称",
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 50,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "所属厂区",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "plant",
      "autoCreated" : false
    }
  }, {
    "id" : 2055156145739904,
    "name" : "命名模式",
    "description" : "设备命名模式的占位符",
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 50,
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055155571251328,
      "dbName" : "idmp",
      "columnName" : "命名模式",
      "sourceDBName" : "db_chemical_demo",
      "sourceChildTable" : "${KEYWORD1}",
      "sourceColumnName" : "namingPattern",
      "autoCreated" : false
    }
  } ],
  "allowExtensions" : true,
  "baseTemplateOnly" : false,
  "keywordsDesc" : {
    "KEYWORD1" : "检测仪名称"
  }
}
