=== huolibo/test/System/Schemas/element.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tdasset.tdengine.com/schemas/element.json",
  "title": "element",
  "description": "schema of a element",
  "type": "object",
  "required": [
    "id",
    "name",
    "generalInfo"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "dirName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "templateId": {
      "type": "number"
    },
    "generalInfo": {
      "$ref": "./general_info.json"
    },
    "attributes": {
      "type": "array",
      "items": {
        "$ref": "./element_attribute.json"
      }
    },
    "templateAttributes": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "elementTempId",
          "attrTempId"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "elementTempId": {
            "type": "number"
          },
          "attrTempId": {
            "type": "number"
          },
          "description": {
            "type": "string"
          },
          "defaultValue": {
            "type": "string"
          },
          "constantItem": {
            "type": "boolean"
          },
          "hidden": {
            "type": "boolean"
          },
          "excluded": {
            "type": "boolean"
          },
          "dataReferenceSetting": {
            "$ref": "./data_reference_setting2.json"
          },
          "valueType": {
            "$ref": "./value_type.json"
          },
          "valueLength": {
            "type": "integer"
          },
          "childAttributes": {
            "type": "array",
            "items": {
              "$ref": "#/properties/templateAttributes/items"
            }
          },
          "traits": {
            "type": "array",
            "items": {
              "$ref": "#/properties/templateAttributes/items"
            }
          }
        }
      }
    },
    "analyses": {
      "type": "array",
      "items": {
        "$ref": "./analysis.json"
      }
    },
    "parents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "referenceType": {
            "enum": [
              "ParentChild",
              "Weak",
              "Composition"
            ]
          },
          "order": {
            "type": "number"
          }
        }
      }
    },
    "notifyRule": {
      "$ref": "./notify_rule.json"
    }
  }
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯化亚砜厂/Children/mysql模板/meta.json
{
  "id" : 2055478834518144,
  "name" : "mysql模板",
  "templateId" : 2055478444214400,
  "dirName" : "mysql模板",
  "generalInfo" : {
    "createTime" : 1790660862051,
    "categories" : [ ],
    "location" : { },
    "additionalAttributes" : [ ],
    "virtualStableName" : "vst_mysql模板_mo90en",
    "virtualTableName" : "vt_mysql模板_t9q6h1",
    "keywordValues" : {
      "KEYWORD1" : "demo"
    }
  },
  "attributes" : [ {
    "id" : 2055478833105024,
    "name" : "tag",
    "description" : "",
    "constantItem" : false,
    "hidden" : false,
    "excluded" : false,
    "categories" : [ 23 ],
    "valueType" : "Varchar",
    "valueLength" : 64,
    "defaultValue" : "",
    "dataReferenceSetting" : {
      "dataReferenceType" : "TDengineTag",
      "connectionId" : 2055478375004288,
      "dbName" : "idmp",
      "targetConnectionId" : 2055155571251328,
      "childTable" : "vt_mysql模板_t9q6h1",
      "columnName" : "tag",
      "sourceDBName" : "idmp",
      "sourceTimestampColumnName" : "ts",
      "tagQueryMode" : "SIMPLE",
      "tagReadMode" : "LATEST_ROW",
      "sourceChildTable" : "demo",
      "sourceColumnName" : "name",
      "verified" : true,
      "autoCreated" : false
    },
    "additionalProperties" : [ ],
    "attrTempId" : 2055478767712384
  } ],
  "parents" : [ {
    "id" : 2055156148332672,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯化亚砜厂/Children/主反应釜 R-101/meta.json
{
  "id" : 2055156148750464,
  "name" : "主反应釜 R-101",
  "description" : "间歇反应釜",
  "templateId" : 2055156139915392,
  "dirName" : "主反应釜 R-101",
  "generalInfo" : {
    "createTime" : 1790582081292,
    "location" : {
      "altitude" : 3760.286259458085,
      "latitude" : -38.24793798295281,
      "longitude" : -150.40136835424255
    },
    "virtualStableName" : "vst_间歇反应设备_nq0wah",
    "virtualTableName" : "vt_主反应釜 R-101_7r1weu",
    "keywordValues" : {
      "KEYWORD1" : "reactor_101"
    }
  },
  "attributes" : [ {
    "id" : 2055156148779141,
    "defaultValue" : "主反应釜 R-101",
    "attrTempId" : 2055156142205056
  }, {
    "id" : 2055156148779142,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156142504064
  } ],
  "parents" : [ {
    "id" : 2055156148332672,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/仓储中心/Children/仓储区电表 WH-01/meta.json
{
  "id" : 2055156155271296,
  "name" : "仓储区电表 WH-01",
  "description" : "能源计量表",
  "templateId" : 2055156146022528,
  "dirName" : "仓储区电表 WH-01",
  "generalInfo" : {
    "createTime" : 1790582082879,
    "location" : {
      "altitude" : 4866.066268246121,
      "latitude" : 66.78154173940581,
      "longitude" : 117.51451782891564
    },
    "virtualStableName" : "vst_能源计量表_i7i6zt",
    "virtualTableName" : "vt_仓储区电表 WH-01_cvf1r9",
    "keywordValues" : {
      "KEYWORD1" : "meter_wh_01"
    }
  },
  "attributes" : [ {
    "id" : 2055156155279489,
    "defaultValue" : "仓储区电表 WH-01",
    "attrTempId" : 2055156146526336
  }, {
    "id" : 2055156155279490,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156146833536
  } ],
  "parents" : [ {
    "id" : 2055156155046016,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯化亚砜厂/meta.json
{
  "id" : 2055156148332672,
  "name" : "氯化亚砜厂",
  "templateId" : 2055156139219072,
  "dirName" : "氯化亚砜厂",
  "generalInfo" : {
    "createTime" : 1790582081189,
    "virtualStableName" : "vst_厂区中心_7gmvqs",
    "virtualTableName" : "vt_氯化亚砜厂_q86jao",
    "pathName" : "氯化亚砜厂"
  },
  "attributes" : [ ],
  "parents" : [ {
    "id" : 2055156148131968,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/公用工程中心/meta.json
{
  "id" : 2055156155938944,
  "name" : "公用工程中心",
  "templateId" : 2055156139219072,
  "dirName" : "公用工程中心",
  "generalInfo" : {
    "createTime" : 1790582083042,
    "virtualStableName" : "vst_厂区中心_7gmvqs",
    "virtualTableName" : "vt_公用工程中心_76memw",
    "pathName" : "公用工程中心"
  },
  "attributes" : [ ],
  "parents" : [ {
    "id" : 2055156148131968,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/仓储中心/meta.json
{
  "id" : 2055156155046016,
  "name" : "仓储中心",
  "templateId" : 2055156139219072,
  "dirName" : "仓储中心",
  "generalInfo" : {
    "createTime" : 1790582082824,
    "virtualStableName" : "vst_厂区中心_7gmvqs",
    "virtualTableName" : "vt_仓储中心_ea3737",
    "pathName" : "仓储中心"
  },
  "attributes" : [ ],
  "parents" : [ {
    "id" : 2055156148131968,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯化亚砜厂/Children/在线气相色谱仪 GC-01/meta.json
{
  "id" : 2055156149471360,
  "name" : "在线气相色谱仪 GC-01",
  "description" : "质检中心设备",
  "templateId" : 2055156144650368,
  "dirName" : "在线气相色谱仪 GC-01",
  "generalInfo" : {
    "createTime" : 1790582081463,
    "location" : {
      "altitude" : 5273.069340374878,
      "latitude" : 41.968726580446486,
      "longitude" : 157.63710922214352
    },
    "virtualStableName" : "vst_质检中心设备_qnidoz",
    "virtualTableName" : "vt_在线气相色谱仪 GC-01_araq87",
    "keywordValues" : {
      "KEYWORD1" : "gc_01"
    }
  },
  "attributes" : [ {
    "id" : 2055156149479554,
    "defaultValue" : "在线气相色谱仪 GC-01",
    "attrTempId" : 2055156145457280
  }, {
    "id" : 2055156149479555,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156145739904
  } ],
  "parents" : [ {
    "id" : 2055156148332672,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯化亚砜厂/Children/备用反应釜 R-102/meta.json
{
  "id" : 2055156150077568,
  "name" : "备用反应釜 R-102",
  "description" : "间歇反应釜",
  "templateId" : 2055156139915392,
  "dirName" : "备用反应釜 R-102",
  "generalInfo" : {
    "createTime" : 1790582081611,
    "location" : {
      "altitude" : 3760.286259458085,
      "latitude" : -38.24793798295281,
      "longitude" : -150.40136835424255
    },
    "virtualStableName" : "vst_间歇反应设备_nq0wah",
    "virtualTableName" : "vt_备用反应釜 R-102_s02wt6",
    "keywordValues" : {
      "KEYWORD1" : "reactor_102"
    }
  },
  "attributes" : [ {
    "id" : 2055156150085765,
    "defaultValue" : "主反应釜 R-101",
    "attrTempId" : 2055156142205056
  }, {
    "id" : 2055156150085766,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156142504064
  } ],
  "parents" : [ {
    "id" : 2055156148332672,
    "referenceType" : "ParentChild"
  } ]
}
