=== huolibo/test/System/Schemas/element.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tdasset.tdengine.com/schemas/element.json",
  "title": "element",
  "description": "schema of a element",
  "type": "object",
  "required": [
    "id",
    "name",
    "generalInfo"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "dirName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "templateId": {
      "type": "number"
    },
    "generalInfo": {
      "$ref": "./general_info.json"
    },
    "attributes": {
      "type": "array",
      "items": {
        "$ref": "./element_attribute.json"
      }
    },
    "templateAttributes": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "elementTempId",
          "attrTempId"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "elementTempId": {
            "type": "number"
          },
          "attrTempId": {
            "type": "number"
          },
          "description": {
            "type": "string"
          },
          "defaultValue": {
            "type": "string"
          },
          "constantItem": {
            "type": "boolean"
          },
          "hidden": {
            "type": "boolean"
          },
          "excluded": {
            "type": "boolean"
          },
          "dataReferenceSetting": {
            "$ref": "./data_reference_setting2.json"
          },
          "valueType": {
            "$ref": "./value_type.json"
          },
          "valueLength": {
            "type": "integer"
          },
          "childAttributes": {
            "type": "array",
            "items": {
              "$ref": "#/properties/templateAttributes/items"
            }
          },
          "traits": {
            "type": "array",
            "items": {
              "$ref": "#/properties/templateAttributes/items"
            }
          }
        }
      }
    },
    "analyses": {
      "type": "array",
      "items": {
        "$ref": "./analysis.json"
      }
    },
    "parents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "referenceType": {
            "enum": [
              "ParentChild",
              "Weak",
              "Composition"
            ]
          },
          "order": {
            "type": "number"
          }
        }
      }
    },
    "notifyRule": {
      "$ref": "./notify_rule.json"
    }
  }
}

=== huolibo/test/Elements/Children/某化工集团/Children/公用工程中心/Children/产线总水表 W01/meta.json
{
  "id" : 2055156156168320,
  "name" : "产线总水表 W01",
  "description" : "能源计量表",
  "templateId" : 2055156146022528,
  "dirName" : "产线总水表 W01",
  "generalInfo" : {
    "createTime" : 1790582083099,
    "location" : {
      "altitude" : 4866.066268246121,
      "latitude" : 66.78154173940581,
      "longitude" : 117.51451782891564
    },
    "virtualStableName" : "vst_能源计量表_i7i6zt",
    "virtualTableName" : "vt_产线总水表 W01_rfvlx2",
    "keywordValues" : {
      "KEYWORD1" : "meter_w01"
    }
  },
  "attributes" : [ {
    "id" : 2055156156180609,
    "defaultValue" : "产线总电表 E01",
    "attrTempId" : 2055156146526336
  }, {
    "id" : 2055156156180610,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156146833536
  } ],
  "parents" : [ {
    "id" : 2055156155938944,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯化亚砜厂/Children/循环水泵 P-202/meta.json
{
  "id" : 2055156151396480,
  "name" : "循环水泵 P-202",
  "description" : "连续动力设备",
  "templateId" : 2055156142794880,
  "dirName" : "循环水泵 P-202",
  "generalInfo" : {
    "createTime" : 1790582081933,
    "location" : {
      "altitude" : 308.1036630235405,
      "latitude" : -44.46118949602416,
      "longitude" : 114.67028126524986
    },
    "virtualStableName" : "vst_连续动力设备_gl6ss4",
    "virtualTableName" : "vt_循环水泵 P-202_xc4wn3",
    "keywordValues" : {
      "KEYWORD1" : "pump_202"
    }
  },
  "attributes" : [ {
    "id" : 2055156151404675,
    "defaultValue" : "循环水泵 P-201",
    "attrTempId" : 2055156143814784
  }, {
    "id" : 2055156151404676,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156144339072
  } ],
  "parents" : [ {
    "id" : 2055156148332672,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯碱厂/meta.json
{
  "id" : 2055156151957632,
  "name" : "氯碱厂",
  "templateId" : 2055156139219072,
  "dirName" : "氯碱厂",
  "generalInfo" : {
    "createTime" : 1790582082071,
    "virtualStableName" : "vst_厂区中心_7gmvqs",
    "virtualTableName" : "vt_氯碱厂_zurvq3",
    "pathName" : "氯碱厂"
  },
  "attributes" : [ ],
  "parents" : [ {
    "id" : 2055156148131968,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/AC厂/Children/离心机 CF-101/meta.json
{
  "id" : 2055156154599552,
  "name" : "离心机 CF-101",
  "description" : "连续动力设备",
  "templateId" : 2055156142794880,
  "dirName" : "离心机 CF-101",
  "generalInfo" : {
    "createTime" : 1790582082714,
    "location" : {
      "altitude" : 308.1036630235405,
      "latitude" : -44.46118949602416,
      "longitude" : 114.67028126524986
    },
    "virtualStableName" : "vst_连续动力设备_gl6ss4",
    "virtualTableName" : "vt_离心机 CF-101_1ky6cr",
    "keywordValues" : {
      "KEYWORD1" : "centrifuge_101"
    }
  },
  "attributes" : [ {
    "id" : 2055156154603651,
    "defaultValue" : "离心机 CF-101",
    "attrTempId" : 2055156143814784
  }, {
    "id" : 2055156154603652,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156144339072
  } ],
  "parents" : [ {
    "id" : 2055156153895040,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/AC厂/meta.json
{
  "id" : 2055156153895040,
  "name" : "AC厂",
  "templateId" : 2055156139219072,
  "dirName" : "AC厂",
  "generalInfo" : {
    "createTime" : 1790582082542,
    "virtualStableName" : "vst_厂区中心_7gmvqs",
    "virtualTableName" : "vt_AC厂_3g75p4",
    "pathName" : "AC厂"
  },
  "attributes" : [ ],
  "parents" : [ {
    "id" : 2055156148131968,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/AC厂/Children/合成釜 A-101/meta.json
{
  "id" : 2055156154132608,
  "name" : "合成釜 A-101",
  "description" : "间歇反应釜",
  "templateId" : 2055156139915392,
  "dirName" : "合成釜 A-101",
  "generalInfo" : {
    "createTime" : 1790582082601,
    "location" : {
      "altitude" : 3760.286259458085,
      "latitude" : -38.24793798295281,
      "longitude" : -150.40136835424255
    },
    "virtualStableName" : "vst_间歇反应设备_nq0wah",
    "virtualTableName" : "vt_合成釜 A-101_gjz5zm",
    "keywordValues" : {
      "KEYWORD1" : "reactor_a101"
    }
  },
  "attributes" : [ {
    "id" : 2055156154140805,
    "defaultValue" : "合成釜 A-101",
    "attrTempId" : 2055156142205056
  }, {
    "id" : 2055156154140806,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156142504064
  } ],
  "parents" : [ {
    "id" : 2055156153895040,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/公用工程中心/Children/产线总电表 E02/meta.json
{
  "id" : 2055156159105152,
  "name" : "产线总电表 E02",
  "description" : "能源计量表",
  "templateId" : 2055156146022528,
  "dirName" : "产线总电表 E02",
  "generalInfo" : {
    "createTime" : 1790582083818,
    "location" : {
      "altitude" : 4866.066268246121,
      "latitude" : 66.78154173940581,
      "longitude" : 117.51451782891564
    },
    "virtualStableName" : "vst_能源计量表_i7i6zt",
    "virtualTableName" : "vt_产线总电表 E02_b19adu",
    "keywordValues" : {
      "KEYWORD1" : "meter_e02"
    }
  },
  "attributes" : [ {
    "id" : 2055156159125633,
    "defaultValue" : "产线总电表 E01",
    "attrTempId" : 2055156146526336
  }, {
    "id" : 2055156159125634,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156146833536
  } ],
  "parents" : [ {
    "id" : 2055156155938944,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/公用工程中心/Children/燃煤锅炉 B-01/meta.json
{
  "id" : 2055156159977600,
  "name" : "燃煤锅炉 B-01",
  "description" : "能源计量表",
  "templateId" : 2055156146022528,
  "dirName" : "燃煤锅炉 B-01",
  "generalInfo" : {
    "createTime" : 1790582084030,
    "location" : {
      "altitude" : 4866.066268246121,
      "latitude" : 66.78154173940581,
      "longitude" : 117.51451782891564
    },
    "virtualStableName" : "vst_能源计量表_i7i6zt",
    "virtualTableName" : "vt_燃煤锅炉 B-01_q3pf1g",
    "keywordValues" : {
      "KEYWORD1" : "boiler_b01"
    }
  },
  "attributes" : [ {
    "id" : 2055156159993985,
    "defaultValue" : "产线总电表 E01",
    "attrTempId" : 2055156146526336
  }, {
    "id" : 2055156159993986,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156146833536
  } ],
  "parents" : [ {
    "id" : 2055156155938944,
    "referenceType" : "ParentChild"
  } ]
}
