=== huolibo/test/System/Schemas/element.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tdasset.tdengine.com/schemas/element.json",
  "title": "element",
  "description": "schema of a element",
  "type": "object",
  "required": [
    "id",
    "name",
    "generalInfo"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "dirName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "templateId": {
      "type": "number"
    },
    "generalInfo": {
      "$ref": "./general_info.json"
    },
    "attributes": {
      "type": "array",
      "items": {
        "$ref": "./element_attribute.json"
      }
    },
    "templateAttributes": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "elementTempId",
          "attrTempId"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "elementTempId": {
            "type": "number"
          },
          "attrTempId": {
            "type": "number"
          },
          "description": {
            "type": "string"
          },
          "defaultValue": {
            "type": "string"
          },
          "constantItem": {
            "type": "boolean"
          },
          "hidden": {
            "type": "boolean"
          },
          "excluded": {
            "type": "boolean"
          },
          "dataReferenceSetting": {
            "$ref": "./data_reference_setting2.json"
          },
          "valueType": {
            "$ref": "./value_type.json"
          },
          "valueLength": {
            "type": "integer"
          },
          "childAttributes": {
            "type": "array",
            "items": {
              "$ref": "#/properties/templateAttributes/items"
            }
          },
          "traits": {
            "type": "array",
            "items": {
              "$ref": "#/properties/templateAttributes/items"
            }
          }
        }
      }
    },
    "analyses": {
      "type": "array",
      "items": {
        "$ref": "./analysis.json"
      }
    },
    "parents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "referenceType": {
            "enum": [
              "ParentChild",
              "Weak",
              "Composition"
            ]
          },
          "order": {
            "type": "number"
          }
        }
      }
    },
    "notifyRule": {
      "$ref": "./notify_rule.json"
    }
  }
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯碱厂/Children/电解槽 E-101/meta.json
{
  "id" : 2055156153399424,
  "name" : "电解槽 E-101",
  "description" : "连续动力设备",
  "templateId" : 2055156142794880,
  "dirName" : "电解槽 E-101",
  "generalInfo" : {
    "createTime" : 1790582082422,
    "location" : {
      "altitude" : 308.1036630235405,
      "latitude" : -44.46118949602416,
      "longitude" : 114.67028126524986
    },
    "virtualStableName" : "vst_连续动力设备_gl6ss4",
    "virtualTableName" : "vt_电解槽 E-101_7khdky",
    "keywordValues" : {
      "KEYWORD1" : "electrolyzer_101"
    }
  },
  "attributes" : [ {
    "id" : 2055156153407619,
    "defaultValue" : "氯气压缩机 C-301",
    "attrTempId" : 2055156143814784
  }, {
    "id" : 2055156153407620,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156144339072
  } ],
  "parents" : [ {
    "id" : 2055156151957632,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯碱厂/Children/氯气压缩机 C-301/meta.json
{
  "id" : 2055156152875136,
  "name" : "氯气压缩机 C-301",
  "description" : "连续动力设备",
  "templateId" : 2055156142794880,
  "dirName" : "氯气压缩机 C-301",
  "generalInfo" : {
    "createTime" : 1790582082295,
    "location" : {
      "altitude" : 308.1036630235405,
      "latitude" : -44.46118949602416,
      "longitude" : 114.67028126524986
    },
    "virtualStableName" : "vst_连续动力设备_gl6ss4",
    "virtualTableName" : "vt_氯气压缩机 C-301_kmg9l8",
    "keywordValues" : {
      "KEYWORD1" : "comp_301"
    }
  },
  "attributes" : [ {
    "id" : 2055156152883331,
    "defaultValue" : "氯气压缩机 C-301",
    "attrTempId" : 2055156143814784
  }, {
    "id" : 2055156152883332,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156144339072
  } ],
  "parents" : [ {
    "id" : 2055156151957632,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/氯碱厂/Children/氢气压缩机 C-302/meta.json
{
  "id" : 2055156152342656,
  "name" : "氢气压缩机 C-302",
  "description" : "连续动力设备",
  "templateId" : 2055156142794880,
  "dirName" : "氢气压缩机 C-302",
  "generalInfo" : {
    "createTime" : 1790582082166,
    "location" : {
      "altitude" : 308.1036630235405,
      "latitude" : -44.46118949602416,
      "longitude" : 114.67028126524986
    },
    "virtualStableName" : "vst_连续动力设备_gl6ss4",
    "virtualTableName" : "vt_氢气压缩机 C-302_q3qi50",
    "keywordValues" : {
      "KEYWORD1" : "comp_302"
    }
  },
  "attributes" : [ {
    "id" : 2055156152359043,
    "defaultValue" : "氯气压缩机 C-301",
    "attrTempId" : 2055156143814784
  }, {
    "id" : 2055156152359044,
    "defaultValue" : "${KEYWORD1}",
    "attrTempId" : 2055156144339072
  } ],
  "parents" : [ {
    "id" : 2055156151957632,
    "referenceType" : "ParentChild"
  } ]
}

=== huolibo/test/Elements/Children/某化工集团/Children/化验室/meta.json
{
  "id" : 2055156160866432,
  "name" : "化验室",
  "templateId" : 2055156139219072,
  "dirName" : "化验室",
  "generalInfo" : {
    "createTime" : 1790582084249,
    "virtualStableName" : "vst_厂区中心_7gmvqs",
    "virtualTableName" : "vt_化验室_iy1fu7",
    "pathName" : "化验室"
  },
  "attributes" : [ ],
  "parents" : [ {
    "id" : 2055156148131968,
    "referenceType" : "ParentChild"
  } ]
}
