=== huolibo/test/System/Schemas/notification_template.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "type": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "title": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "content": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "type",
    "name"
  ]
}

=== huolibo/test/System/Notifications/templates/1891659426828796.json
{
  "id": 1891659426828796,
  "name": "feishu.panel.notification",
  "description": "Panel Snapshot Notification for Feishu",
  "type": "Feishu",
  "title": {
    "zh-CN": "{elementName} 的{type} - {dashboardPanelName}",
    "en": "{type} of {elementName} - {dashboardPanelName}",
    "es": "{type} de {elementName} - {dashboardPanelName}",
    "ko": "{elementName}의 {type} - {dashboardPanelName}"
  },
  "content": {
    "zh-CN": "报告名称：{dashboardPanelName}\n元素：{elementName}\n生成时间：{reportTime}",
    "en": "Report: {dashboardPanelName}\nElement: {elementName}\nReport Time: {reportTime}",
    "es": "Informe: {dashboardPanelName}\nElemento: {elementName}\nHora del informe: {reportTime}",
    "ko": "보고서: {dashboardPanelName}\n요소: {elementName}\n보고서 시간: {reportTime}"
  }
}

=== huolibo/test/System/Notifications/templates/1845973038761473.json
{
  "id": 1845973038761473,
  "name": "email.user.invite",
  "description": "TDengine IDMP invite user",
  "type": "Mail",
  "title": {
    "zh-CN": "邀请您加入 TDengine IDMP",
    "en": "Invitation to TDengine IDMP",
    "es": "Invitación a TDengine IDMP",
    "ko": "TDengine IDMP 초대"
  },
  "content": {
    "zh-CN": "<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\"/>\n<style type=\"text/css\"> p {\n  font-family: Amazon Ember, Helvetica Neue, Roboto, Arial, sans-serif;\n  font-weight: 400;\n  line-height: 25px;\n  font-size: 16px;\n  margin: 0px auto;\n}\n\n.td_email_body {\n  width: 100%;\n  background-color: #D4D7DD;\n  padding-top: 30px;\n  padding-bottom: 30px;\n}\n\n.td_email_content {\n  background-color: #fff;\n  padding: 0px;\n  margin: 0px;\n  width: 700px;\n  margin: 0 auto;\n  padding: 30px 50px;\n}</style>\n<div class=\"td_email_body\">\n  <div class=\"td_email_content\"><p>{userEmail} 您好，</p><br>\n    <p>{organization} 的管理员已为您注册了 TDengine IDMP，单击下面的按钮激活您的账户。<br/></p>\n    <p><a style=\"height: 40px; background-color: #0052CC; color: #fff; line-height: 40px; display: inline-block; padding: 0px 20px; margin: 10px 0; opacity: 1; border-radius: 5px;\" href=\"{serverUrl}/activate?code={validationCode}&org={encryptOrgId}&backend={assetAddress}\">点击激活</a><br/></p>\n    <p>请注意，该链接为临时链接，将在 24 小时后过期。\n    </p><br>\n    <p>请务必为您的登录链接添加书签，以便以后轻松访问您的账户。 如果您在登录账户时遇到任何问题，请联系 <a href=\"mailto:cloud@taosdata.com\" style=\"color: #0052CC;\">cloud@taosdata.com</a>。</p>\n    <p><span>如果您有其他问题，欢迎致电 4006120020 或访问</span><a href=\"https://www.taosdata.com/\">TDengine 官网</a><span>联系我们。</span></p>\n    <br>\n    <p>谢谢，</p>\n    <p>TDengine 团队</p></div>\n</div>\n",
    "en": "<p>Hi {userEmail},</p>\n<p>You have been invited to work together in TDengine IDMP by the administrator of {organization}.</p>\n<p><strong><a href=\"{serverUrl}/activate?code={validationCode}&org={encryptOrgId}&backend={assetAddress}\">Click here to activate your account and get started.</a></strong>\nIt's really that easy!</p>\n<p>Note that this activation link is temporary and will expire in 24 hours.</p>\n<p>If you experience any problems logging in to your account, contact us at <a href=\"mailto:support@tdengine.com\">support@tdengine.com</a>.</p>\n<p>Regards,</p>\n<p>The TDengine Team</p>",
    "es": "<p>Hola {userEmail},</p>\n<p>Ha sido invitado a colaborar en TDengine IDMP por el administrador de {organization}.</p>\n<p><strong><a href=\"{serverUrl}/activate?code={validationCode}&org={encryptOrgId}&backend={assetAddress}\">Haga clic aquí para activar su cuenta y comenzar.</a></strong>\n¡Es así de fácil!</p>\n<p>Tenga en cuenta que este enlace de activación es temporal y caducará en 24 horas.</p>\n<p>Si tiene problemas para iniciar sesión en su cuenta, contáctenos en <a href=\"mailto:support@tdengine.com\">support@tdengine.com</a>.</p>\n<p>Saludos,</p>\n<p>El equipo de TDengine</p>",
    "ko": "<p>{userEmail}님, 안녕하세요,</p>\n<p>{organization}의 관리자가 TDengine IDMP에서 함께 작업하도록 초대했습니다.</p>\n<p><strong><a href=\"{serverUrl}/activate?code={validationCode}&org={encryptOrgId}&backend={assetAddress}\">계정을 활성화하고 시작하려면 여기를 클릭하세요.</a></strong>\n정말 간단합니다!</p>\n<p>이 활성화 링크는 임시 링크이며 24시간 후에 만료됩니다.</p>\n<p>계정 로그인에 문제가 있으시면 다음으로 문의해 주세요: <a href=\"mailto:support@tdengine.com\">support@tdengine.com</a>.</p>\n<p>감사합니다,</p>\n<p>TDengine 팀</p>"
  }
}

=== huolibo/test/System/Notifications/templates/1845972925555840.json
{
  "id": 1845972925555840,
  "name": "email.password.reset.request",
  "description": "Password Reset Request",
  "type": "Mail",
  "title": {
    "zh-CN": "重置您的 TDengine IDMP 账户密码",
    "en": "Reset Your TDengine IDMP Password",
    "es": "Restablezca su contraseña de TDengine IDMP",
    "ko": "TDengine IDMP 비밀번호 재설정"
  },
  "content": {
    "zh-CN": "<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\"/>\n<style type=\"text/css\"> p {\n  font-family: Amazon Ember, Helvetica Neue, Roboto, Arial, sans-serif;\n  font-weight: 400;\n  line-height: 25px;\n  font-size: 16px;\n  margin: 0px auto;\n}\n\n.td_email_body {\n  width: 100%;\n  background-color: #D4D7DD;\n  padding-top: 30px;\n  padding-bottom: 30px;\n}\n\n.td_email_content {\n  background-color: #fff;\n  padding: 0px;\n  margin: 0px;\n  width: 700px;\n  margin: 0 auto;\n  padding: 30px 50px;\n}</style>\n<div class=\"td_email_body\">\n  <div class=\"td_email_content\"><p>{userName} 您好，</p><br/>\n    <p>我们收到了您 TDengine IDMP 账户密码的重置申请。</p>\n    <p>如确认需重置密码，请点击下面的“重置我的密码”按钮。</p>\n    <p><a style=\"height: 40px; background-color: #0052CC; color: #fff; line-height: 40px; display: inline-block; padding: 0px 20px; margin: 10px 0; opacity: 1; border-radius: 5px;\"\n        href=\"{serverUrl}/reset?code={validationCode}\">重置我的密码</a></p>\n    <p>此链接将在 24 小时后过期。 若超时，请再次申请重置。</p>\n    <p>如果您没有提出重置密码的申请，请回复此邮件并告知我们，以便我们帮助您保护您的账户。</p><br>\n    <p>谢谢</p>\n    <p>TDengine 团队</p></div>\n</div>",
    "en": "<p>Hi {userName},</p>\n<p>We received your request to reset your TDengine IDMP password.</p>\n<p><a href=\"{serverUrl}/reset?code={validationCode}\">Click here to reset your password.</a></p>\n<p>This link is valid for 24 hours.</p>\n<p>Note: If you did not request a password reset, please disregard this message.</p>\n<p>Regards,</p>\n<p>The TDengine Team</p>",
    "es": "<p>Hola {userName},</p>\n<p>Hemos recibido su solicitud para restablecer su contraseña de TDengine IDMP.</p>\n<p><a href=\"{serverUrl}/reset?code={validationCode}\">Haga clic aquí para restablecer su contraseña.</a></p>\n<p>Este enlace es válido por 24 horas.</p>\n<p>Nota: Si no solicitó un restablecimiento de contraseña, ignore este mensaje.</p>\n<p>Saludos,</p>\n<p>El equipo de TDengine</p>",
    "ko": "<p>{userName}님, 안녕하세요,</p>\n<p>TDengine IDMP 비밀번호 재설정 요청을 받았습니다.</p>\n<p><a href=\"{serverUrl}/reset?code={validationCode}\">비밀번호를 재설정하려면 여기를 클릭하세요.</a></p>\n<p>이 링크는 24시간 동안 유효합니다.</p>\n<p>참고: 비밀번호 재설정을 요청하지 않으셨다면 이 메시지를 무시해 주세요.</p>\n<p>감사합니다,</p>\n<p>TDengine 팀</p>"
  }
}
