=== huolibo/test/System/Schemas/uom_class.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tdasset.tdengine.com/schemas/category.json",
  "title": "UOM class",
  "description": "schema of an UOM class",
  "type": "object",
  "required": [
    "id",
    "name",
    "canonicalId",
    "uomList"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "number"
    },
    "name": {
      "type": "string",
      "pattern": "^(?!^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\\..*)?$)[^<>:\"/\\\\|?*\\x00-\\x1F]{1,50}$"
    },
    "description": {
      "type": "string"
    },
    "canonicalId": {
      "type": "number"
    },
    "baseClasses": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "power"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "power": {
            "type": "integer"
          }
        }
      }
    },
    "uomList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name",
          "uomClassId",
          "abbreviation",
          "factor",
          "offset"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "uomClassId": {
            "type": "number"
          },
          "abbreviation": {
            "type": "string"
          },
          "factor": {
            "type": "number"
          },
          "offset": {
            "type": "number"
          },
          "refUomId": {
            "type": "number"
          },
          "refFactor": {
            "type": "number"
          },
          "refOffset": {
            "type": "number"
          },
          "origin": {
            "enum": [
              "SystemDefined",
              "UserDefined"
            ]
          }
        }
      }
    }
  }
}

=== huolibo/test/Libraries/UOM/es/Almacenamiento Informático.json
{
  "id" : 241994516,
  "name" : "Almacenamiento Informático",
  "canonicalId" : 110511290,
  "uomList" : [ {
    "id" : 110511290,
    "name" : "byte",
    "uomClassId" : 241994516,
    "abbreviation" : "B",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 421744834,
    "name" : "bit",
    "uomClassId" : 241994516,
    "abbreviation" : "bit",
    "factor" : 0.125,
    "offset" : 0.0,
    "refUomId" : 110511290,
    "refFactor" : 0.125,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 579370092,
    "name" : "kibibyte",
    "uomClassId" : 241994516,
    "abbreviation" : "KiB",
    "factor" : 1024.0,
    "offset" : 0.0,
    "refUomId" : 110511290,
    "refFactor" : 1024.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2063082246,
    "name" : "mebibyte",
    "uomClassId" : 241994516,
    "abbreviation" : "MiB",
    "factor" : 1048576.0,
    "offset" : 0.0,
    "refUomId" : 579370092,
    "refFactor" : 1024.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1591283611,
    "name" : "gibibyte",
    "uomClassId" : 241994516,
    "abbreviation" : "GiB",
    "factor" : 1.073741824E9,
    "offset" : 0.0,
    "refUomId" : 2063082246,
    "refFactor" : 1024.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1064752789,
    "name" : "tebibyte",
    "uomClassId" : 241994516,
    "abbreviation" : "TiB",
    "factor" : 1.099511627776E12,
    "offset" : 0.0,
    "refUomId" : 1591283611,
    "refFactor" : 1024.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1915819476,
    "name" : "pebibyte",
    "uomClassId" : 241994516,
    "abbreviation" : "PiB",
    "factor" : 1.125899906842624E15,
    "offset" : 0.0,
    "refUomId" : 1064752789,
    "refFactor" : 1024.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 296656965,
    "name" : "exbibyte",
    "uomClassId" : 241994516,
    "abbreviation" : "EiB",
    "factor" : 1.152921504606847E18,
    "offset" : 0.0,
    "refUomId" : 1915819476,
    "refFactor" : 1024.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1683458542,
    "name" : "zebibyte",
    "uomClassId" : 241994516,
    "abbreviation" : "ZiB",
    "factor" : 1.1805916207174113E21,
    "offset" : 0.0,
    "refUomId" : 296656965,
    "refFactor" : 1024.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 121482298,
    "name" : "yobibyte",
    "uomClassId" : 241994516,
    "abbreviation" : "YiB",
    "factor" : 1.2089258196146292E24,
    "offset" : 0.0,
    "refUomId" : 1683458542,
    "refFactor" : 1024.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 666000835,
    "name" : "kilobyte",
    "uomClassId" : 241994516,
    "abbreviation" : "kB",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 110511290,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1598581010,
    "name" : "megabyte",
    "uomClassId" : 241994516,
    "abbreviation" : "MB",
    "factor" : 1000000.0,
    "offset" : 0.0,
    "refUomId" : 666000835,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 523077037,
    "name" : "gigabyte",
    "uomClassId" : 241994516,
    "abbreviation" : "GB",
    "factor" : 1.0E9,
    "offset" : 0.0,
    "refUomId" : 1598581010,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2062821956,
    "name" : "terabyte",
    "uomClassId" : 241994516,
    "abbreviation" : "TB",
    "factor" : 1.0E12,
    "offset" : 0.0,
    "refUomId" : 523077037,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1399037172,
    "name" : "petabyte",
    "uomClassId" : 241994516,
    "abbreviation" : "PB",
    "factor" : 1.0E15,
    "offset" : 0.0,
    "refUomId" : 2062821956,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 530635,
    "name" : "exabyte",
    "uomClassId" : 241994516,
    "abbreviation" : "EB",
    "factor" : 1.0E18,
    "offset" : 0.0,
    "refUomId" : 1399037172,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 687742460,
    "name" : "zettabyte",
    "uomClassId" : 241994516,
    "abbreviation" : "ZB",
    "factor" : 1.0E21,
    "offset" : 0.0,
    "refUomId" : 530635,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 297031142,
    "name" : "yottabyte",
    "uomClassId" : 241994516,
    "abbreviation" : "YB",
    "factor" : 1.0E24,
    "offset" : 0.0,
    "refUomId" : 687742460,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/es/Tiempo.json
{
  "id" : 845944798,
  "name" : "Tiempo",
  "canonicalId" : 567863632,
  "uomList" : [ {
    "id" : 567863632,
    "name" : "segundo",
    "uomClassId" : 845944798,
    "abbreviation" : "s",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 60247723,
    "name" : "milisegundo",
    "uomClassId" : 845944798,
    "abbreviation" : "ms",
    "factor" : 0.001,
    "offset" : 0.0,
    "refUomId" : 567863632,
    "refFactor" : 0.001,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 990106351,
    "name" : "minuto",
    "uomClassId" : 845944798,
    "abbreviation" : "min",
    "factor" : 60.0,
    "offset" : 0.0,
    "refUomId" : 567863632,
    "refFactor" : 60.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 340524239,
    "name" : "hora",
    "uomClassId" : 845944798,
    "abbreviation" : "h",
    "factor" : 3600.0,
    "offset" : 0.0,
    "refUomId" : 990106351,
    "refFactor" : 60.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 646056247,
    "name" : "día",
    "uomClassId" : 845944798,
    "abbreviation" : "d",
    "factor" : 86400.0,
    "offset" : 0.0,
    "refUomId" : 340524239,
    "refFactor" : 24.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 452373429,
    "name" : "mes",
    "uomClassId" : 845944798,
    "abbreviation" : "month",
    "factor" : 2628000.000000003,
    "offset" : 0.0,
    "refUomId" : 646056247,
    "refFactor" : 30.4166666666667,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 475595020,
    "name" : "semana",
    "uomClassId" : 845944798,
    "abbreviation" : "week",
    "factor" : 604800.0,
    "offset" : 0.0,
    "refUomId" : 646056247,
    "refFactor" : 7.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 914720599,
    "name" : "año",
    "uomClassId" : 845944798,
    "abbreviation" : "yr",
    "factor" : 3.1536E7,
    "offset" : 0.0,
    "refUomId" : 646056247,
    "refFactor" : 365.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/zh-CN/电流.json
{
  "id": 1778056105,
  "name": "电流",
  "canonicalId": 2144441927,
  "uomList": [
    {
      "id": 2144441927,
      "name": "安培",
      "uomClassId": 1778056105,
      "abbreviation": "A",
      "factor": 1.0,
      "offset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 243641582,
      "name": "毫安",
      "uomClassId": 1778056105,
      "abbreviation": "mA",
      "factor": 0.001,
      "offset": 0.0,
      "refUomId": 2144441927,
      "refFactor": 0.001,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    }
  ]
}

=== huolibo/test/Libraries/UOM/zh-CN/角速度.json
{
  "id": 2107628284,
  "name": "角速度",
  "canonicalId": 1943923865,
  "baseClasses": [
    {
      "id": 729094994,
      "power": 1
    },
    {
      "id": 845944798,
      "power": -1
    }
  ],
  "uomList": [
    {
      "id": 1943923865,
      "name": "弧度每秒",
      "uomClassId": 2107628284,
      "abbreviation": "rad/s",
      "factor": 1.0,
      "offset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1481051919,
      "name": "转每分钟",
      "uomClassId": 2107628284,
      "abbreviation": "rpm",
      "factor": 0.10471975511966,
      "offset": 0.0,
      "refUomId": 1943923865,
      "refFactor": 0.10471975511966,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    }
  ]
}

=== huolibo/test/Libraries/UOM/zh-CN/功率.json
{
  "id": 698156100,
  "name": "功率",
  "canonicalId": 1008149209,
  "baseClasses": [
    {
      "id": 1472482346,
      "power": 2
    },
    {
      "id": 470275444,
      "power": 1
    },
    {
      "id": 845944798,
      "power": -3
    }
  ],
  "uomList": [
    {
      "id": 1008149209,
      "name": "瓦特",
      "uomClassId": 698156100,
      "abbreviation": "W",
      "factor": 1.0,
      "offset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 850360133,
      "name": "吉瓦",
      "uomClassId": 698156100,
      "abbreviation": "GW",
      "factor": 1000000000.0,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 1000000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1115126002,
      "name": "兆瓦",
      "uomClassId": 698156100,
      "abbreviation": "MW",
      "factor": 1000000.0,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 1000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 2085286412,
      "name": "英热单位每小时",
      "uomClassId": 698156100,
      "abbreviation": "Btu/h",
      "factor": 0.29307107017222,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 0.29307107017222,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1234383808,
      "name": "百万英热单位每天",
      "uomClassId": 698156100,
      "abbreviation": "MMBtu/d",
      "factor": 12211.294590509176,
      "offset": 0.0,
      "refUomId": 2085286412,
      "refFactor": 41666.6666666667,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1247776468,
      "name": "百万英热单位每小时",
      "uomClassId": 698156100,
      "abbreviation": "MMBtu/h",
      "factor": 293071.07017222,
      "offset": 0.0,
      "refUomId": 2085286412,
      "refFactor": 1000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1240629474,
      "name": "卡路里每秒",
      "uomClassId": 698156100,
      "abbreviation": "cal/s",
      "factor": 4.1868,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 4.1868,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 273726089,
      "name": "马力",
      "uomClassId": 698156100,
      "abbreviation": "hp",
      "factor": 745.699871582,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 745.699871582,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 892159896,
      "name": "焦耳每秒",
      "uomClassId": 698156100,
      "abbreviation": "J/s",
      "factor": 1.0,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 1.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1381178644,
      "name": "千瓦",
      "uomClassId": 698156100,
      "abbreviation": "kW",
      "factor": 1000.0,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 1000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1665724677,
      "name": "兆焦每小时",
      "uomClassId": 698156100,
      "abbreviation": "MJ/h",
      "factor": 277.777777777778,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 277.777777777778,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1339669146,
      "name": "百万卡路里每小时",
      "uomClassId": 698156100,
      "abbreviation": "Mcal/h",
      "factor": 1163.0,
      "offset": 0.0,
      "refUomId": 1008149209,
      "refFactor": 1163.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    }
  ]
}

=== huolibo/test/Libraries/UOM/ko/평면각.json
{
  "id" : 729094994,
  "name" : "평면각",
  "canonicalId" : 199479158,
  "uomList" : [ {
    "id" : 199479158,
    "name" : "radián",
    "uomClassId" : 729094994,
    "abbreviation" : "rad",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1404381843,
    "name" : "grado",
    "uomClassId" : 729094994,
    "abbreviation" : "°",
    "factor" : 0.0174532925199433,
    "offset" : 0.0,
    "refUomId" : 199479158,
    "refFactor" : 0.0174532925199433,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 292305093,
    "name" : "revolución",
    "uomClassId" : 729094994,
    "abbreviation" : "r",
    "factor" : 6.28318530717959,
    "offset" : 0.0,
    "refUomId" : 199479158,
    "refFactor" : 6.28318530717959,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/ko/비체적.json
{
  "id" : 398067309,
  "name" : "비체적",
  "canonicalId" : 71077421,
  "baseClasses" : [ {
    "id" : 1472482346,
    "power" : 3
  }, {
    "id" : 470275444,
    "power" : -1
  } ],
  "uomList" : [ {
    "id" : 71077421,
    "name" : "metro cúbico por kilogramo",
    "uomClassId" : 398067309,
    "abbreviation" : "m³/kg",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1294206910,
    "name" : "pie cúbico por libra",
    "uomClassId" : 398067309,
    "abbreviation" : "ft³/lb",
    "factor" : 0.0624279605761446,
    "offset" : 0.0,
    "refUomId" : 71077421,
    "refFactor" : 0.0624279605761446,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2128487548,
    "name" : "centímetro cúbico por gramo",
    "uomClassId" : 398067309,
    "abbreviation" : "cm³/g",
    "factor" : 0.001,
    "offset" : 0.0,
    "refUomId" : 71077421,
    "refFactor" : 0.001,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/en/Area.json
{
  "id" : 540622235,
  "name" : "Area",
  "canonicalId" : 577516047,
  "baseClasses" : [ {
    "id" : 1472482346,
    "power" : 2
  } ],
  "uomList" : [ {
    "id" : 577516047,
    "name" : "square meter",
    "uomClassId" : 540622235,
    "abbreviation" : "m²",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 810873665,
    "name" : "square inch",
    "uomClassId" : 540622235,
    "abbreviation" : "in²",
    "factor" : 6.4516E-4,
    "offset" : 0.0,
    "refUomId" : 577516047,
    "refFactor" : 6.4516E-4,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 477031558,
    "name" : "square foot",
    "uomClassId" : 540622235,
    "abbreviation" : "ft²",
    "factor" : 0.09290303999999999,
    "offset" : 0.0,
    "refUomId" : 810873665,
    "refFactor" : 144.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 719663262,
    "name" : "acre",
    "uomClassId" : 540622235,
    "abbreviation" : "ac",
    "factor" : 4046.8564223999997,
    "offset" : 0.0,
    "refUomId" : 477031558,
    "refFactor" : 43560.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1358638177,
    "name" : "square mile",
    "uomClassId" : 540622235,
    "abbreviation" : "mi²",
    "factor" : 2589988.1103359996,
    "offset" : 0.0,
    "refUomId" : 477031558,
    "refFactor" : 2.78784E7,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 80086174,
    "name" : "square yard",
    "uomClassId" : 540622235,
    "abbreviation" : "yd²",
    "factor" : 0.8361273599999999,
    "offset" : 0.0,
    "refUomId" : 477031558,
    "refFactor" : 9.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1237293946,
    "name" : "hectare",
    "uomClassId" : 540622235,
    "abbreviation" : "ha",
    "factor" : 10000.0,
    "offset" : 0.0,
    "refUomId" : 577516047,
    "refFactor" : 10000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2010611611,
    "name" : "square centimeter",
    "uomClassId" : 540622235,
    "abbreviation" : "cm²",
    "factor" : 1.0E-4,
    "offset" : 0.0,
    "refUomId" : 577516047,
    "refFactor" : 1.0E-4,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2110283373,
    "name" : "square kilometer",
    "uomClassId" : 540622235,
    "abbreviation" : "km²",
    "factor" : 1000000.0,
    "offset" : 0.0,
    "refUomId" : 577516047,
    "refFactor" : 1000000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1419612695,
    "name" : "square millimeter",
    "uomClassId" : 540622235,
    "abbreviation" : "mm²",
    "factor" : 1.0E-6,
    "offset" : 0.0,
    "refUomId" : 577516047,
    "refFactor" : 1.0E-6,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}
