=== huolibo/test/System/Schemas/uom_class.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tdasset.tdengine.com/schemas/category.json",
  "title": "UOM class",
  "description": "schema of an UOM class",
  "type": "object",
  "required": [
    "id",
    "name",
    "canonicalId",
    "uomList"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "number"
    },
    "name": {
      "type": "string",
      "pattern": "^(?!^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\\..*)?$)[^<>:\"/\\\\|?*\\x00-\\x1F]{1,50}$"
    },
    "description": {
      "type": "string"
    },
    "canonicalId": {
      "type": "number"
    },
    "baseClasses": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "power"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "power": {
            "type": "integer"
          }
        }
      }
    },
    "uomList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name",
          "uomClassId",
          "abbreviation",
          "factor",
          "offset"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "uomClassId": {
            "type": "number"
          },
          "abbreviation": {
            "type": "string"
          },
          "factor": {
            "type": "number"
          },
          "offset": {
            "type": "number"
          },
          "refUomId": {
            "type": "number"
          },
          "refFactor": {
            "type": "number"
          },
          "refOffset": {
            "type": "number"
          },
          "origin": {
            "enum": [
              "SystemDefined",
              "UserDefined"
            ]
          }
        }
      }
    }
  }
}

=== huolibo/test/Libraries/UOM/zh-CN/能量.json
{
  "id": 623268060,
  "name": "能量",
  "canonicalId": 1318854283,
  "baseClasses": [
    {
      "id": 1472482346,
      "power": 2
    },
    {
      "id": 470275444,
      "power": 1
    },
    {
      "id": 845944798,
      "power": -2
    }
  ],
  "uomList": [
    {
      "id": 1318854283,
      "name": "焦耳",
      "uomClassId": 623268060,
      "abbreviation": "J",
      "factor": 1.0,
      "offset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 717922917,
      "name": "吉瓦时",
      "uomClassId": 623268060,
      "abbreviation": "GWh",
      "factor": 3600000000000.0,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 3600000000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 186555004,
      "name": "兆瓦时",
      "uomClassId": 623268060,
      "abbreviation": "MWh",
      "factor": 3600000000.0,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 3600000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 885559585,
      "name": "瓦时",
      "uomClassId": 623268060,
      "abbreviation": "Wh",
      "factor": 3600.0,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 3600.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1559877794,
      "name": "英热单位",
      "uomClassId": 623268060,
      "abbreviation": "Btu",
      "factor": 1055.05585262,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 1055.05585262,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1368774577,
      "name": "卡路里",
      "uomClassId": 623268060,
      "abbreviation": "cal",
      "factor": 4.1868,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 4.1868,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 189770482,
      "name": "吉焦",
      "uomClassId": 623268060,
      "abbreviation": "GJ",
      "factor": 1000000000.0,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 1000000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1940648592,
      "name": "千焦",
      "uomClassId": 623268060,
      "abbreviation": "kJ",
      "factor": 1000.0,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 1000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 718247581,
      "name": "千瓦时",
      "uomClassId": 623268060,
      "abbreviation": "kWh",
      "factor": 3600000.0,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 3600000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1167425844,
      "name": "兆焦",
      "uomClassId": 623268060,
      "abbreviation": "MJ",
      "factor": 1000000.0,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 1000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 752066640,
      "name": "瓦秒",
      "uomClassId": 623268060,
      "abbreviation": "Ws",
      "factor": 1.0,
      "offset": 0.0,
      "refUomId": 1318854283,
      "refFactor": 1.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 310490055,
      "name": "千卡",
      "uomClassId": 623268060,
      "abbreviation": "kcal",
      "factor": 4186.8,
      "offset": 0.0,
      "refUomId": 1368774577,
      "refFactor": 1000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 1377444084,
      "name": "百万卡路里",
      "uomClassId": 623268060,
      "abbreviation": "Mcal",
      "factor": 4186800.0,
      "offset": 0.0,
      "refUomId": 1368774577,
      "refFactor": 1000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    },
    {
      "id": 253655028,
      "name": "百万英热单位",
      "uomClassId": 623268060,
      "abbreviation": "MMBtu",
      "factor": 1055055852.62,
      "offset": 0.0,
      "refUomId": 1559877794,
      "refFactor": 1000000.0,
      "refOffset": 0.0,
      "origin": "SystemDefined"
    }
  ]
}

=== huolibo/test/Libraries/UOM/ko/전력.json
{
  "id" : 698156100,
  "name" : "전력",
  "canonicalId" : 1008149209,
  "baseClasses" : [ {
    "id" : 1472482346,
    "power" : 2
  }, {
    "id" : 470275444,
    "power" : 1
  }, {
    "id" : 845944798,
    "power" : -3
  } ],
  "uomList" : [ {
    "id" : 1008149209,
    "name" : "vatio",
    "uomClassId" : 698156100,
    "abbreviation" : "W",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 850360133,
    "name" : "gigavatio",
    "uomClassId" : 698156100,
    "abbreviation" : "GW",
    "factor" : 1.0E9,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1.0E9,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1115126002,
    "name" : "megavatio",
    "uomClassId" : 698156100,
    "abbreviation" : "MW",
    "factor" : 1000000.0,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1000000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2085286412,
    "name" : "unidad térmica británica por hora",
    "uomClassId" : 698156100,
    "abbreviation" : "Btu/h",
    "factor" : 0.29307107017222,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 0.29307107017222,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1234383808,
    "name" : "millón de unidades térmicas británicas por día",
    "uomClassId" : 698156100,
    "abbreviation" : "MMBtu/d",
    "factor" : 12211.294590509176,
    "offset" : 0.0,
    "refUomId" : 2085286412,
    "refFactor" : 41666.6666666667,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1247776468,
    "name" : "millón de unidades térmicas británicas por hora",
    "uomClassId" : 698156100,
    "abbreviation" : "MMBtu/h",
    "factor" : 293071.07017222,
    "offset" : 0.0,
    "refUomId" : 2085286412,
    "refFactor" : 1000000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1240629474,
    "name" : "caloría por segundo",
    "uomClassId" : 698156100,
    "abbreviation" : "cal/s",
    "factor" : 4.1868,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 4.1868,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 273726089,
    "name" : "caballo de fuerza",
    "uomClassId" : 698156100,
    "abbreviation" : "hp",
    "factor" : 745.699871582,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 745.699871582,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 892159896,
    "name" : "julio por segundo",
    "uomClassId" : 698156100,
    "abbreviation" : "J/s",
    "factor" : 1.0,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1381178644,
    "name" : "kilovatio",
    "uomClassId" : 698156100,
    "abbreviation" : "kW",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1665724677,
    "name" : "megajulio por hora",
    "uomClassId" : 698156100,
    "abbreviation" : "MJ/h",
    "factor" : 277.777777777778,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 277.777777777778,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1339669146,
    "name" : "millón de calorías por hora",
    "uomClassId" : 698156100,
    "abbreviation" : "Mcal/h",
    "factor" : 1163.0,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1163.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/en/Mass Flow Rate.json
{
  "id" : 2125678082,
  "name" : "Mass Flow Rate",
  "canonicalId" : 247719873,
  "baseClasses" : [ {
    "id" : 470275444,
    "power" : 1
  }, {
    "id" : 845944798,
    "power" : -1
  } ],
  "uomList" : [ {
    "id" : 247719873,
    "name" : "kilogram per second",
    "uomClassId" : 2125678082,
    "abbreviation" : "kg/s",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 982917432,
    "name" : "pound per second",
    "uomClassId" : 2125678082,
    "abbreviation" : "lb/s",
    "factor" : 0.45359237,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.45359237,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2105628535,
    "name" : "tonne per day",
    "uomClassId" : 2125678082,
    "abbreviation" : "t/d",
    "factor" : 0.0115740740740741,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.0115740740740741,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1157785121,
    "name" : "tonne per hour",
    "uomClassId" : 2125678082,
    "abbreviation" : "t/h",
    "factor" : 0.2777777777777784,
    "offset" : 0.0,
    "refUomId" : 2105628535,
    "refFactor" : 24.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 830347335,
    "name" : "kilogram per hour",
    "uomClassId" : 2125678082,
    "abbreviation" : "kg/h",
    "factor" : 2.7777777777777843E-4,
    "offset" : 0.0,
    "refUomId" : 1157785121,
    "refFactor" : 0.001,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1771654855,
    "name" : "pounds per hour",
    "uomClassId" : 2125678082,
    "abbreviation" : "lb/h",
    "factor" : 1.2599788065635386E-4,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 2.77777778E-4,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1165290943,
    "name" : "thousand pounds per hour",
    "uomClassId" : 2125678082,
    "abbreviation" : "klb/h",
    "factor" : 0.12599788065635387,
    "offset" : 0.0,
    "refUomId" : 1771654855,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2065847461,
    "name" : "kilopounds per hour",
    "uomClassId" : 2125678082,
    "abbreviation" : "kilopounds per hour",
    "factor" : 0.12599788065635387,
    "offset" : 0.0,
    "refUomId" : 1165290943,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1065707907,
    "name" : "pounds per day",
    "uomClassId" : 2125678082,
    "abbreviation" : "lb/d",
    "factor" : 0.0030239491357524927,
    "offset" : 0.0,
    "refUomId" : 1771654855,
    "refFactor" : 24.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 721225899,
    "name" : "thousand lb per hr",
    "uomClassId" : 2125678082,
    "abbreviation" : "k lb/hr",
    "factor" : 0.12599788065635387,
    "offset" : 0.0,
    "refUomId" : 1165290943,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 352067532,
    "name" : "tons per hour",
    "uomClassId" : 2125678082,
    "abbreviation" : "tons/hr",
    "factor" : 0.2777777777777784,
    "offset" : 0.0,
    "refUomId" : 1157785121,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1499165909,
    "name" : "t/hr",
    "uomClassId" : 2125678082,
    "abbreviation" : "t/hr",
    "factor" : 0.2777777777777784,
    "offset" : 0.0,
    "refUomId" : 2105628535,
    "refFactor" : 24.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1520141513,
    "name" : "hundredweight per second",
    "uomClassId" : 2125678082,
    "abbreviation" : "cwt/s",
    "factor" : 45.359237,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 45.359237,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1600661954,
    "name" : "hundredweight per minute",
    "uomClassId" : 2125678082,
    "abbreviation" : "cwt/min",
    "factor" : 0.755987283333333,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.755987283333333,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1828378175,
    "name" : "hundredweight per hour",
    "uomClassId" : 2125678082,
    "abbreviation" : "cwt/h",
    "factor" : 0.0125997880555556,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.0125997880555556,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1452505486,
    "name" : "kilogram per day",
    "uomClassId" : 2125678082,
    "abbreviation" : "kg/d",
    "factor" : 1.15740740740741E-5,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 1.15740740740741E-5,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1601168059,
    "name" : "kilogram per minute",
    "uomClassId" : 2125678082,
    "abbreviation" : "kg/min",
    "factor" : 0.0166666666666667,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.0166666666666667,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1399024197,
    "name" : "tons per minute",
    "uomClassId" : 2125678082,
    "abbreviation" : "t/min",
    "factor" : 16.6666666666667,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 16.6666666666667,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1917863760,
    "name" : "short ton per hour",
    "uomClassId" : 2125678082,
    "abbreviation" : "ST/h",
    "factor" : 0.25199576111111116,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 0.5555555555555556,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 979865772,
    "name" : "long ton per day",
    "uomClassId" : 2125678082,
    "abbreviation" : "LT/d",
    "factor" : 0.011759802185185174,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 0.0259259259259259,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 303708890,
    "name" : "million pound per day",
    "uomClassId" : 2125678082,
    "abbreviation" : "MMlb/d",
    "factor" : 5.249911689814827,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 11.5740740740741,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1858172197,
    "name" : "short ton per day",
    "uomClassId" : 2125678082,
    "abbreviation" : "ST/d",
    "factor" : 0.010499823379629607,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 0.0231481481481481,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 274164892,
    "name" : "thousand pound per day",
    "uomClassId" : 2125678082,
    "abbreviation" : "klb/d",
    "factor" : 0.005249911689814826,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 0.0115740740740741,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 892178640,
    "name" : "gram per second",
    "uomClassId" : 2125678082,
    "abbreviation" : "g/s",
    "factor" : 0.001,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.001,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/en/Pressure.json
{
  "id" : 264033646,
  "name" : "Pressure",
  "canonicalId" : 2030839396,
  "baseClasses" : [ {
    "id" : 1472482346,
    "power" : -1
  }, {
    "id" : 470275444,
    "power" : 1
  }, {
    "id" : 845944798,
    "power" : -2
  } ],
  "uomList" : [ {
    "id" : 2030839396,
    "name" : "pascal",
    "uomClassId" : 264033646,
    "abbreviation" : "Pa",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 40365770,
    "name" : "atmosphere",
    "uomClassId" : 264033646,
    "abbreviation" : "atm",
    "factor" : 101325.0,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 101325.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 4899462,
    "name" : "bar",
    "uomClassId" : 264033646,
    "abbreviation" : "bar",
    "factor" : 100000.0,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 100000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 135923569,
    "name" : "inches of mercury",
    "uomClassId" : 264033646,
    "abbreviation" : "inHg",
    "factor" : 3386.38815789,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 3386.38815789,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1557203432,
    "name" : "kilogram-force per square centimeter",
    "uomClassId" : 264033646,
    "abbreviation" : "kgf/cm²",
    "factor" : 98066.5,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 98066.5,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 164186548,
    "name" : "kilogram-force per square meter",
    "uomClassId" : 264033646,
    "abbreviation" : "kgf/m²",
    "factor" : 9.80665,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 9.80665,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1753955006,
    "name" : "kilopascal",
    "uomClassId" : 264033646,
    "abbreviation" : "kPa",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 228230395,
    "name" : "millimeter of mercury",
    "uomClassId" : 264033646,
    "abbreviation" : "mmHg",
    "factor" : 133.322368421,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 133.322368421,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1014380924,
    "name" : "newton per square meter",
    "uomClassId" : 264033646,
    "abbreviation" : "N/m²",
    "factor" : 1.0,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 419698709,
    "name" : "pound-force per square inch",
    "uomClassId" : 264033646,
    "abbreviation" : "psi",
    "factor" : 6894.75729316836,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 6894.75729316836,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1803342654,
    "name" : "pound-force per square inch (customary)",
    "uomClassId" : 264033646,
    "abbreviation" : "psia",
    "factor" : 6894.75729316836,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 6894.75729316836,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1731794251,
    "name" : "torr",
    "uomClassId" : 264033646,
    "abbreviation" : "torr",
    "factor" : 133.322368421,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 133.322368421,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/ko/압력.json
{
  "id" : 264033646,
  "name" : "압력",
  "canonicalId" : 2030839396,
  "baseClasses" : [ {
    "id" : 1472482346,
    "power" : -1
  }, {
    "id" : 470275444,
    "power" : 1
  }, {
    "id" : 845944798,
    "power" : -2
  } ],
  "uomList" : [ {
    "id" : 2030839396,
    "name" : "pascal",
    "uomClassId" : 264033646,
    "abbreviation" : "Pa",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 40365770,
    "name" : "atmósfera",
    "uomClassId" : 264033646,
    "abbreviation" : "atm",
    "factor" : 101325.0,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 101325.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 4899462,
    "name" : "bar",
    "uomClassId" : 264033646,
    "abbreviation" : "bar",
    "factor" : 100000.0,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 100000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 135923569,
    "name" : "pulgadas de mercurio",
    "uomClassId" : 264033646,
    "abbreviation" : "inHg",
    "factor" : 3386.38815789,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 3386.38815789,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1557203432,
    "name" : "kilogramo-fuerza por centímetro cuadrado",
    "uomClassId" : 264033646,
    "abbreviation" : "kgf/cm²",
    "factor" : 98066.5,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 98066.5,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 164186548,
    "name" : "kilogramo-fuerza por metro cuadrado",
    "uomClassId" : 264033646,
    "abbreviation" : "kgf/m²",
    "factor" : 9.80665,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 9.80665,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1753955006,
    "name" : "kilopascal",
    "uomClassId" : 264033646,
    "abbreviation" : "kPa",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 228230395,
    "name" : "milímetro de mercurio",
    "uomClassId" : 264033646,
    "abbreviation" : "mmHg",
    "factor" : 133.322368421,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 133.322368421,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1014380924,
    "name" : "newton por metro cuadrado",
    "uomClassId" : 264033646,
    "abbreviation" : "N/m²",
    "factor" : 1.0,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 419698709,
    "name" : "libra-fuerza por pulgada cuadrada",
    "uomClassId" : 264033646,
    "abbreviation" : "psi",
    "factor" : 6894.75729316836,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 6894.75729316836,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1803342654,
    "name" : "libra-fuerza por pulgada cuadrada (habitual)",
    "uomClassId" : 264033646,
    "abbreviation" : "psia",
    "factor" : 6894.75729316836,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 6894.75729316836,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1731794251,
    "name" : "torr",
    "uomClassId" : 264033646,
    "abbreviation" : "torr",
    "factor" : 133.322368421,
    "offset" : 0.0,
    "refUomId" : 2030839396,
    "refFactor" : 133.322368421,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/es/Caudal Molar.json
{
  "id" : 2103261239,
  "name" : "Caudal Molar",
  "canonicalId" : 242301649,
  "baseClasses" : [ {
    "id" : 427058508,
    "power" : 1
  }, {
    "id" : 845944798,
    "power" : -1
  } ],
  "uomList" : [ {
    "id" : 242301649,
    "name" : "mol por segundo",
    "uomClassId" : 2103261239,
    "abbreviation" : "mol/s",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1727399913,
    "name" : "gramo mol por segundo",
    "uomClassId" : 2103261239,
    "abbreviation" : "gmol/s",
    "factor" : 1.0,
    "offset" : 0.0,
    "refUomId" : 242301649,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2146761200,
    "name" : "kilogramo mol por segundo",
    "uomClassId" : 2103261239,
    "abbreviation" : "kmol/s",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 242301649,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1369132567,
    "name" : "libra mol por segundo",
    "uomClassId" : 2103261239,
    "abbreviation" : "lbmol/s",
    "factor" : 453.59237,
    "offset" : 0.0,
    "refUomId" : 242301649,
    "refFactor" : 453.59237,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/en/Specific Volume.json
{
  "id" : 398067309,
  "name" : "Specific Volume",
  "canonicalId" : 71077421,
  "baseClasses" : [ {
    "id" : 1472482346,
    "power" : 3
  }, {
    "id" : 470275444,
    "power" : -1
  } ],
  "uomList" : [ {
    "id" : 71077421,
    "name" : "cubic meter per kilogram",
    "uomClassId" : 398067309,
    "abbreviation" : "m³/kg",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1294206910,
    "name" : "cubic foot per pound",
    "uomClassId" : 398067309,
    "abbreviation" : "ft³/lb",
    "factor" : 0.0624279605761446,
    "offset" : 0.0,
    "refUomId" : 71077421,
    "refFactor" : 0.0624279605761446,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2128487548,
    "name" : "cubic centimeter per gram",
    "uomClassId" : 398067309,
    "abbreviation" : "cm³/g",
    "factor" : 0.001,
    "offset" : 0.0,
    "refUomId" : 71077421,
    "refFactor" : 0.001,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/en/Moles.json
{
  "id" : 427058508,
  "name" : "Moles",
  "canonicalId" : 1310010803,
  "uomList" : [ {
    "id" : 1310010803,
    "name" : "mole",
    "uomClassId" : 427058508,
    "abbreviation" : "mol",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 845596542,
    "name" : "gram mole",
    "uomClassId" : 427058508,
    "abbreviation" : "gmol",
    "factor" : 1.0,
    "offset" : 0.0,
    "refUomId" : 1310010803,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1356916839,
    "name" : "kilogram mole",
    "uomClassId" : 427058508,
    "abbreviation" : "kmol",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 1310010803,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 481163204,
    "name" : "pound mole",
    "uomClassId" : 427058508,
    "abbreviation" : "lbmol",
    "factor" : 453.59237,
    "offset" : 0.0,
    "refUomId" : 1310010803,
    "refFactor" : 453.59237,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}
