=== huolibo/test/System/Schemas/uom_class.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tdasset.tdengine.com/schemas/category.json",
  "title": "UOM class",
  "description": "schema of an UOM class",
  "type": "object",
  "required": [
    "id",
    "name",
    "canonicalId",
    "uomList"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "number"
    },
    "name": {
      "type": "string",
      "pattern": "^(?!^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\\..*)?$)[^<>:\"/\\\\|?*\\x00-\\x1F]{1,50}$"
    },
    "description": {
      "type": "string"
    },
    "canonicalId": {
      "type": "number"
    },
    "baseClasses": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "power"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "power": {
            "type": "integer"
          }
        }
      }
    },
    "uomList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name",
          "uomClassId",
          "abbreviation",
          "factor",
          "offset"
        ],
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "uomClassId": {
            "type": "number"
          },
          "abbreviation": {
            "type": "string"
          },
          "factor": {
            "type": "number"
          },
          "offset": {
            "type": "number"
          },
          "refUomId": {
            "type": "number"
          },
          "refFactor": {
            "type": "number"
          },
          "refOffset": {
            "type": "number"
          },
          "origin": {
            "enum": [
              "SystemDefined",
              "UserDefined"
            ]
          }
        }
      }
    }
  }
}

=== huolibo/test/Libraries/UOM/en/Electric Charge.json
{
  "id" : 1766342711,
  "name" : "Electric Charge",
  "canonicalId" : 189606822,
  "baseClasses" : [ {
    "id" : 1778056105,
    "power" : 1
  }, {
    "id" : 845944798,
    "power" : 1
  } ],
  "uomList" : [ {
    "id" : 189606822,
    "name" : "coulomb",
    "uomClassId" : 1766342711,
    "abbreviation" : "C",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1343383959,
    "name" : "Ampere hour",
    "uomClassId" : 1766342711,
    "abbreviation" : "Ah",
    "factor" : 3600.0,
    "offset" : 0.0,
    "refUomId" : 189606822,
    "refFactor" : 3600.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/zh-CN/频率.json
{
  "id": 2062763077,
  "name": "频率",
  "canonicalId": 719750786,
  "baseClasses": [
    {
      "id": 845944798,
      "power": -1
    }
  ],
  "uomList": [
    {
      "id": 719750786,
      "name": "赫兹",
      "uomClassId": 2062763077,
      "abbreviation": "Hz",
      "factor": 1.0,
      "offset": 0.0,
      "origin": "SystemDefined"
    }
  ]
}

=== huolibo/test/Libraries/UOM/ko/질량 유량.json
{
  "id" : 2125678082,
  "name" : "질량 유량",
  "canonicalId" : 247719873,
  "baseClasses" : [ {
    "id" : 470275444,
    "power" : 1
  }, {
    "id" : 845944798,
    "power" : -1
  } ],
  "uomList" : [ {
    "id" : 247719873,
    "name" : "kilogramo por segundo",
    "uomClassId" : 2125678082,
    "abbreviation" : "kg/s",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 982917432,
    "name" : "libra por segundo",
    "uomClassId" : 2125678082,
    "abbreviation" : "lb/s",
    "factor" : 0.45359237,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.45359237,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2105628535,
    "name" : "tonelada por día",
    "uomClassId" : 2125678082,
    "abbreviation" : "t/d",
    "factor" : 0.0115740740740741,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.0115740740740741,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1157785121,
    "name" : "tonelada por hora",
    "uomClassId" : 2125678082,
    "abbreviation" : "t/h",
    "factor" : 0.2777777777777784,
    "offset" : 0.0,
    "refUomId" : 2105628535,
    "refFactor" : 24.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 830347335,
    "name" : "kilogramo por hora",
    "uomClassId" : 2125678082,
    "abbreviation" : "kg/h",
    "factor" : 2.7777777777777843E-4,
    "offset" : 0.0,
    "refUomId" : 1157785121,
    "refFactor" : 0.001,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1771654855,
    "name" : "libras por hora",
    "uomClassId" : 2125678082,
    "abbreviation" : "lb/h",
    "factor" : 1.2599788065635386E-4,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 2.77777778E-4,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1165290943,
    "name" : "mil libras por hora",
    "uomClassId" : 2125678082,
    "abbreviation" : "klb/h",
    "factor" : 0.12599788065635387,
    "offset" : 0.0,
    "refUomId" : 1771654855,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2065847461,
    "name" : "kilolibras por hora",
    "uomClassId" : 2125678082,
    "abbreviation" : "kilopounds per hour",
    "factor" : 0.12599788065635387,
    "offset" : 0.0,
    "refUomId" : 1165290943,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1065707907,
    "name" : "libras por día",
    "uomClassId" : 2125678082,
    "abbreviation" : "lb/d",
    "factor" : 0.0030239491357524927,
    "offset" : 0.0,
    "refUomId" : 1771654855,
    "refFactor" : 24.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 721225899,
    "name" : "mil lb por hr",
    "uomClassId" : 2125678082,
    "abbreviation" : "k lb/hr",
    "factor" : 0.12599788065635387,
    "offset" : 0.0,
    "refUomId" : 1165290943,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 352067532,
    "name" : "toneladas por hora",
    "uomClassId" : 2125678082,
    "abbreviation" : "tons/hr",
    "factor" : 0.2777777777777784,
    "offset" : 0.0,
    "refUomId" : 1157785121,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1499165909,
    "name" : "t/hr",
    "uomClassId" : 2125678082,
    "abbreviation" : "t/hr",
    "factor" : 0.2777777777777784,
    "offset" : 0.0,
    "refUomId" : 2105628535,
    "refFactor" : 24.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1520141513,
    "name" : "quintal por segundo",
    "uomClassId" : 2125678082,
    "abbreviation" : "cwt/s",
    "factor" : 45.359237,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 45.359237,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1600661954,
    "name" : "quintal por minuto",
    "uomClassId" : 2125678082,
    "abbreviation" : "cwt/min",
    "factor" : 0.755987283333333,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.755987283333333,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1828378175,
    "name" : "quintal por hora",
    "uomClassId" : 2125678082,
    "abbreviation" : "cwt/h",
    "factor" : 0.0125997880555556,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.0125997880555556,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1452505486,
    "name" : "kilogramo por día",
    "uomClassId" : 2125678082,
    "abbreviation" : "kg/d",
    "factor" : 1.15740740740741E-5,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 1.15740740740741E-5,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1601168059,
    "name" : "kilogramo por minuto",
    "uomClassId" : 2125678082,
    "abbreviation" : "kg/min",
    "factor" : 0.0166666666666667,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.0166666666666667,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1399024197,
    "name" : "toneladas por minuto",
    "uomClassId" : 2125678082,
    "abbreviation" : "t/min",
    "factor" : 16.6666666666667,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 16.6666666666667,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1917863760,
    "name" : "tonelada corta por hora",
    "uomClassId" : 2125678082,
    "abbreviation" : "ST/h",
    "factor" : 0.25199576111111116,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 0.5555555555555556,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 979865772,
    "name" : "tonelada larga por día",
    "uomClassId" : 2125678082,
    "abbreviation" : "LT/d",
    "factor" : 0.011759802185185174,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 0.0259259259259259,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 303708890,
    "name" : "millón de libras por día",
    "uomClassId" : 2125678082,
    "abbreviation" : "MMlb/d",
    "factor" : 5.249911689814827,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 11.5740740740741,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1858172197,
    "name" : "tonelada corta por día",
    "uomClassId" : 2125678082,
    "abbreviation" : "ST/d",
    "factor" : 0.010499823379629607,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 0.0231481481481481,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 274164892,
    "name" : "mil libras por día",
    "uomClassId" : 2125678082,
    "abbreviation" : "klb/d",
    "factor" : 0.005249911689814826,
    "offset" : 0.0,
    "refUomId" : 982917432,
    "refFactor" : 0.0115740740740741,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 892178640,
    "name" : "gramo por segundo",
    "uomClassId" : 2125678082,
    "abbreviation" : "g/s",
    "factor" : 0.001,
    "offset" : 0.0,
    "refUomId" : 247719873,
    "refFactor" : 0.001,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/zh-CN/电阻.json
{
  "id": 954571684,
  "name": "电阻",
  "canonicalId": 1721097864,
  "baseClasses": [
    {
      "id": 1778056105,
      "power": -2
    },
    {
      "id": 1472482346,
      "power": 2
    },
    {
      "id": 470275444,
      "power": 1
    },
    {
      "id": 845944798,
      "power": -3
    }
  ],
  "uomList": [
    {
      "id": 1721097864,
      "name": "欧姆",
      "uomClassId": 954571684,
      "abbreviation": "Ω",
      "factor": 1.0,
      "offset": 0.0,
      "origin": "SystemDefined"
    }
  ]
}

=== huolibo/test/Libraries/UOM/en/Specific Energy.json
{
  "id" : 77568021,
  "name" : "Specific Energy",
  "canonicalId" : 735832839,
  "baseClasses" : [ {
    "id" : 1472482346,
    "power" : 2
  }, {
    "id" : 845944798,
    "power" : -2
  } ],
  "uomList" : [ {
    "id" : 735832839,
    "name" : "joule per kilogram",
    "uomClassId" : 77568021,
    "abbreviation" : "J/kg",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2111679991,
    "name" : "joule per gram",
    "uomClassId" : 77568021,
    "abbreviation" : "J/g",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 735832839,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 335629833,
    "name" : "British thermal unit per pound",
    "uomClassId" : 77568021,
    "abbreviation" : "Btu/lb",
    "factor" : 2326.0,
    "offset" : 0.0,
    "refUomId" : 735832839,
    "refFactor" : 2326.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2111068636,
    "name" : "kilocalorie per kilogram",
    "uomClassId" : 77568021,
    "abbreviation" : "kcal/kg",
    "factor" : 4186.8,
    "offset" : 0.0,
    "refUomId" : 735832839,
    "refFactor" : 4186.8,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1859108039,
    "name" : "kilojoule per kilogram",
    "uomClassId" : 77568021,
    "abbreviation" : "kJ/kg",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 735832839,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1053402345,
    "name" : "kilojoule per pound",
    "uomClassId" : 77568021,
    "abbreviation" : "kJ/lb",
    "factor" : 2204.62262184878,
    "offset" : 0.0,
    "refUomId" : 735832839,
    "refFactor" : 2204.62262184878,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/ko/주파수.json
{
  "id" : 2062763077,
  "name" : "주파수",
  "canonicalId" : 719750786,
  "baseClasses" : [ {
    "id" : 845944798,
    "power" : -1
  } ],
  "uomList" : [ {
    "id" : 719750786,
    "name" : "hercio",
    "uomClassId" : 2062763077,
    "abbreviation" : "Hz",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/en/Power.json
{
  "id" : 698156100,
  "name" : "Power",
  "canonicalId" : 1008149209,
  "baseClasses" : [ {
    "id" : 1472482346,
    "power" : 2
  }, {
    "id" : 470275444,
    "power" : 1
  }, {
    "id" : 845944798,
    "power" : -3
  } ],
  "uomList" : [ {
    "id" : 1008149209,
    "name" : "watt",
    "uomClassId" : 698156100,
    "abbreviation" : "W",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 850360133,
    "name" : "gigawatt",
    "uomClassId" : 698156100,
    "abbreviation" : "GW",
    "factor" : 1.0E9,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1.0E9,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1115126002,
    "name" : "megawatt",
    "uomClassId" : 698156100,
    "abbreviation" : "MW",
    "factor" : 1000000.0,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1000000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 2085286412,
    "name" : "British thermal unit per hour",
    "uomClassId" : 698156100,
    "abbreviation" : "Btu/h",
    "factor" : 0.29307107017222,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 0.29307107017222,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1234383808,
    "name" : "million British thermal unit per day",
    "uomClassId" : 698156100,
    "abbreviation" : "MMBtu/d",
    "factor" : 12211.294590509176,
    "offset" : 0.0,
    "refUomId" : 2085286412,
    "refFactor" : 41666.6666666667,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1247776468,
    "name" : "million British thermal unit per hour",
    "uomClassId" : 698156100,
    "abbreviation" : "MMBtu/h",
    "factor" : 293071.07017222,
    "offset" : 0.0,
    "refUomId" : 2085286412,
    "refFactor" : 1000000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1240629474,
    "name" : "calorie per second",
    "uomClassId" : 698156100,
    "abbreviation" : "cal/s",
    "factor" : 4.1868,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 4.1868,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 273726089,
    "name" : "horsepower",
    "uomClassId" : 698156100,
    "abbreviation" : "hp",
    "factor" : 745.699871582,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 745.699871582,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 892159896,
    "name" : "joule per second",
    "uomClassId" : 698156100,
    "abbreviation" : "J/s",
    "factor" : 1.0,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1381178644,
    "name" : "kilowatt",
    "uomClassId" : 698156100,
    "abbreviation" : "kW",
    "factor" : 1000.0,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1000.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1665724677,
    "name" : "megajoule per hour",
    "uomClassId" : 698156100,
    "abbreviation" : "MJ/h",
    "factor" : 277.777777777778,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 277.777777777778,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1339669146,
    "name" : "million calorie per hour",
    "uomClassId" : 698156100,
    "abbreviation" : "Mcal/h",
    "factor" : 1163.0,
    "offset" : 0.0,
    "refUomId" : 1008149209,
    "refFactor" : 1163.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}

=== huolibo/test/Libraries/UOM/en/Molecular Weight.json
{
  "id" : 578696372,
  "name" : "Molecular Weight",
  "canonicalId" : 1137858007,
  "baseClasses" : [ {
    "id" : 470275444,
    "power" : 1
  }, {
    "id" : 427058508,
    "power" : -1
  } ],
  "uomList" : [ {
    "id" : 1137858007,
    "name" : "kilogram per mole",
    "uomClassId" : 578696372,
    "abbreviation" : "kg/mol",
    "factor" : 1.0,
    "offset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 182420754,
    "name" : "kilogram per kilogram mole",
    "uomClassId" : 578696372,
    "abbreviation" : "kg/kmol",
    "factor" : 0.001,
    "offset" : 0.0,
    "refUomId" : 1137858007,
    "refFactor" : 0.001,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 1727450655,
    "name" : "gram per gram mole",
    "uomClassId" : 578696372,
    "abbreviation" : "g/gmol",
    "factor" : 0.001,
    "offset" : 0.0,
    "refUomId" : 182420754,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  }, {
    "id" : 431569722,
    "name" : "pound per pound mole",
    "uomClassId" : 578696372,
    "abbreviation" : "lb/lbmol",
    "factor" : 0.001,
    "offset" : 0.0,
    "refUomId" : 182420754,
    "refFactor" : 1.0,
    "refOffset" : 0.0,
    "origin" : "SystemDefined"
  } ]
}
